# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homepage.models
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('korporative', 'korporativ'), ('einzelne', 'einzeln')], default='korporative', max_length=20)),
                ('firma', models.CharField(blank=True, max_length=50)),
                ('anrede', models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], default='Frau', max_length=10)),
                ('titel', models.CharField(blank=True, choices=[('', ''), ('Dr.', 'Dr.')], default='', max_length=10)),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=50)),
                ('land', models.CharField(max_length=2)),
                ('email_firma', models.EmailField(blank=True, max_length=50, verbose_name='Email gesch\xe4ftlich')),
                ('email_privat', models.EmailField(blank=True, max_length=50, verbose_name='Email privat')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='Anhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('datei', models.FileField(max_length=255, upload_to=homepage.models.anhang_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anhang',
                'verbose_name_plural': 'Anh\xe4nge',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=homepage.models.foto_image_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='FotoGalerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fotogalerie',
                'verbose_name_plural': 'Fotogalerien',
            },
        ),
        migrations.CreateModel(
            name='Neuigkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('inhalt', tinymce.models.HTMLField()),
                ('datum', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Neuigkeit',
                'verbose_name_plural': 'Neuigkeiten',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=homepage.models.partner_image_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partner',
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='galerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.FotoGalerie'),
        ),
        migrations.AddField(
            model_name='anhang',
            name='neuigkeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Neuigkeit'),
        ),
    ]
